# Site default meta keywords
#keywords: site, wide, default, keywords

menu:
  Home: /
  Archives: /archives

highlight:
  enable: false

widgets:
- search
# - category
# - tagcloud
# - tag
# - about
# - subscribe_mailchimp
# - noteworthy

# For use with tagcloud or tag widgets
# - only tags >= to tag_minium are shown
tag_minium: 3

about:
  title: About John Doe
  content:
  - image: /images/john.jpg
    image_alt: John
    description: I'm a python developer
  - image: /images/rust.jpg
    image_alt: Rust
    description: Recently I started learning rust.

noteworthy_title: Some important posts
noteworthy:
  - url: /2001/01/01/post-1
    title: Important post 1
  - url: /2001/01/01/post-2
    title: Important post 2

recommended_links_title: You'll also find me on
recommended_links:
  - url: https://stackoverflow.com/users/1234/user_name
    title: Stackoverflow
  - url: https://github.com/user_name
    title: Github
  - url: https://www.linkedin.com/in/usre_name/
    title: LinkedIn

# Mailchimp:
# 
# to set up mailing over Mailchimp create a campaign based on RSS
#
# to get those ids, go to Mailchimp and go to
# lists -> embedded -> naked
# see copy/paste onto site:

mailchimp:
  # inside <form action="…">
  post_action: ""
  # inside <input type="text" name="…" tabindex="-1" value="">
  field_name: 



twitter_id:
facebook_id:
linkedin_id:
github_id:
google_plus_id: 

disqus_shortname: 


highlightjs: solarized-light

# highlightjs color schemes available (try https://highlightjs.org/static/demo/ for a demo)
# agate
# androidstudio
# arduino-light
# arta
# ascetic
# atelier-cave-dark
# atelier-cave-light
# atelier-dune-dark
# atelier-dune-light
# atelier-estuary-dark
# atelier-estuary-light
# atelier-forest-dark
# atelier-forest-light
# atelier-heath-dark
# atelier-heath-light
# atelier-lakeside-dark
# atelier-lakeside-light
# atelier-plateau-dark
# atelier-plateau-light
# atelier-savanna-dark
# atelier-savanna-light
# atelier-seaside-dark
# atelier-seaside-light
# atelier-sulphurpool-dark
# atelier-sulphurpool-light
# atom-one-dark
# atom-one-light
# brown_paper
# brown-paper
# brown_papersq.png            
# brown-papersq.png            
# codepen-embed
# color-brewer
# darcula
# dark
# darkula
# default
# docco
# dracula
# far
# foundation
# github
# github-gist
# googlecode
# grayscale
# gruvbox-dark
# gruvbox-light
# hopscotch
# hybrid
# idea
# ir_black
# ir-black
# kimbie.dark
# kimbie.light
# magula
# mono-blue
# monokai
# monokai_sublime
# monokai-sublime
# obsidian
# ocean
# paraiso-dark
# paraiso-light
# pojoaque
# pojoaque.jpg
# purebasic
# qtcreator_dark
# qtcreator_light
# railscasts
# rainbow
# routeros
# school_book
# school-book
# school_book.png
# school-book.png
# solarized_dark
# solarized-dark
# solarized_dark_old
# solarized_light
# solarized-light
# sunburst
# tomorrow
# tomorrow-night-blue
# tomorrow-night-bright
# tomorrow-night
# tomorrow-night-eighties
# vs2015
# vs
# xcode
# xt256
# zenburn

